### ISSUE TITLE
Spark jobs stuck in submitted state and fails

### ISSUE THREAD

**Issue by KailashBallu** [melodyyangaws/karpenter-emr-on-eks#1]
I followed this workshop but unable to get the spark jobs working. 
NAME                        READY   STATUS    RESTARTS   AGE
00000003326m5n64alr-7ngl8   0/2     Pending   0          14m 

Looked at the pods logs and can see the following:
kube-system   49m                    Warning   FailedCreatePodSandBox    Pod/coredns-55fb5d545d-phcqh                              Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b583f69b9c4c324c269a940952bd57333010f26626889d16d1322633e01b4a0f": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: Error received from AddNetwork gRPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"

what am I doing wrong?

**Comment by melodyyangaws** [comment]
did you use the script [create-workshop-env.sh](https://github.com/melodyyangaws/karpenter-emr-on-eks/blob/main/provision/create-workshop-env.sh) to create your EKS cluster? Was there any errors? What's the result of these commands:
```
kubectl get node --label-columns=app,topology.kubernetes.io/zone,node.kubernetes.io/instance-type,eks.amazonaws.com/nodegroup

kubectl get po -A
```

**Comment by KailashBallu** [comment]
Hi Melody,

Thank you for getting back to me. I believe the problem I am having is with
Karpenter provisioner. See below:
Release "karpenter" does not exist. Installing it now.
NAME: karpenter
LAST DEPLOYED: Fri Dec  8 01:53:06 2023
NAMESPACE: karpenter
STATUS: deployed
REVISION: 1
TEST SUITE: None
Error from server (InternalError): error when creating
"karpenter/k-provisioner.yaml": Internal error occurred: failed calling
webhook "defaulting.webhook.provisioners.karpenter.sh": failed to call
webhook: Post "https://karpenter.karpenter.svc:443/?timeout=10s": no
endpoints available for service "karpenter"
configmap/config-logging patched

Regards,
Kailash

**Comment by KailashBallu** [comment]
Hi Melody,
yes, I am using the create-workshop-env.sh
<https://github.com/melodyyangaws/karpenter-emr-on-eks/blob/main/provision/create-workshop-env.sh>
 script

The outputs of the two commands:

I am running the script - ./example/sample-job-karpenter.sh

kubectl get node
--label-columns=app,topology.kubernetes.io/zone,node.kubernetes.io/instance-type,eks.amazonaws.com/nodegroup

NAME                             STATUS   ROLES    AGE     VERSION
           APP       ZONE         INSTANCE-TYPE   NODEGROUP
ip-192-168-11-242.ec2.internal   Ready    <none>   9m56s
v1.26.10-eks-e71965b   ops       us-east-1a   c4.large
tfc-summit-ops
ip-192-168-44-37.ec2.internal    Ready    <none>   16m
v1.26.10-eks-e71965b   caspark   us-east-1b   c5.4xlarge
tfc-summit-spotip-192-168-78-239.ec2.internal   Ready    <none>   16m
   v1.26.10-eks-e71965b   ops       us-east-1c   c4.large
tfc-summit-ops

kubectl get po -A

NAMESPACE     NAME
READY   STATUS    RESTARTS   AGE
emr           0000000332752p76als-tklj7                            0/2
    Pending   0          3m8s
karpenter     karpenter-7958645cc-99kf2                            2/2
    Running   0          11m
karpenter     karpenter-7958645cc-mtknq                            2/2
    Running   0          11m
kube-system   aws-node-8w6kc                                       1/1
    Running   0          17m
kube-system   aws-node-9l9n8                                       1/1
    Running   0          17m
kube-system   aws-node-ql5kh                                       1/1
    Running   0          10m
kube-system   coredns-55fb5d545d-7c2vt                             1/1
    Running   0          28m
kube-system   coredns-55fb5d545d-hkhbt                             1/1
    Running   0          28m
kube-system   kube-proxy-jszfk                                     1/1
    Running   0          10m
kube-system   kube-proxy-nb8tz                                     1/1
    Running   0          17m
kube-system   kube-proxy-pqrp5                                     1/1
    Running   0          17m
kube-system   metrics-server-d9694457-txbrc                        1/1
    Running   0          11m
kube-system   nodescaler-aws-cluster-autoscaler-648fbbf4b9-g7bm4   1/1
    Running   0          15m


Regards,

Kailash

**Comment by KailashBallu** [comment]
Hi Melody,

I applied the k-provisioner.yaml script and everything seems to be working.
Thank you very much for all your help

NAME                               READY   STATUS    RESTARTS   AGE
000000033276hohojfq-nz2j4          2/2     Running   0          3m31s
emr-eks-karpenter-exec-1           1/1     Running   0          95s
emr-eks-karpenter-exec-10          0/1     Pending   0          93s
emr-eks-karpenter-exec-11          0/1     Pending   0          92s
emr-eks-karpenter-exec-12          0/1     Pending   0          92s
emr-eks-karpenter-exec-13          0/1     Pending   0          92s
emr-eks-karpenter-exec-14          0/1     Pending   0          92s
emr-eks-karpenter-exec-15          0/1     Pending   0          92s
emr-eks-karpenter-exec-16          0/1     Pending   0          91s

Every 1.0s: kubectl get node --label-columns=
node.kubernetes.io/instance-type,karpenter.sh/capacity-type,eks.amazonaws.com/capacityType,topology.kubernetes.io/zone,app
        ip-10-138-185-45.ec2.internal: Fri Dec  8 02:18:17 2023

NAME                              STATUS   ROLES    AGE     VERSION
       INSTANCE-TYPE   CAPACITY-TYPE   CAPACITYTYPE   ZONE         APP
ip-192-168-106-216.ec2.internal   Ready    <none>   97s
v1.21.14-eks-48e63af   c5n.4xlarge     on-demand
 us-east-1a   kspark
ip-192-168-11-242.ec2.internal    Ready    <none>   24m
v1.26.10-eks-e71965b   c4.large                        ON_DEMAND
 us-east-1a   ops
ip-192-168-24-234.ec2.internal    Ready    <none>   3m37s
v1.21.14-eks-48e63af   c5a.2xlarge     on-demand
 us-east-1a   kspark
ip-192-168-44-37.ec2.internal     Ready    <none>   30m
v1.26.10-eks-e71965b   c5.4xlarge                      SPOT
us-east-1b   caspark
ip-192-168-6-241.ec2.internal     Ready    <none>   30s
v1.21.14-eks-48e63af   c5n.4xlarge     spot
us-east-1a   kspark
ip-192-168-78-239.ec2.internal    Ready    <none>   30m
v1.26.10-eks-e71965b   c4.large                        ON_DEMAND
 us-east-1c   ops

Regards,
Kailash

**Comment by melodyyangaws** [comment]
great to hear that Kailash!
